name: check

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  pack:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          pattern: build-*
          merge-multiple: true

      - name: Install
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: lts/*

      - name: Pack
        run: pnpm pack

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: package
          path: '*.tgz'
