name: release

on:
  push:
    tags: ['*']

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: build

      - name: Install
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: lts/*
          node-registry-url: https://registry.npmjs.org

      - name: Update npm
        run: npm install -g npm@latest

      - name: Publish
        run: npm publish --access=public --tag=${{ contains(github.ref, 'alpha') && 'alpha' || contains(github.ref, 'beta') && 'beta' || 'latest' }}
